##
# WordPress
##

version: '3.9'

services:

  nginx:
    image: nginx:1.21.3
    container_name: wordpress_nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/wordpress.test:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx:/var/log/nginx

  php:
    build: ./conf/php
    depends_on:
     - mariadb
    container_name: wordpress_php
    restart: always
    volumes:
      - .:/var/www/wordpress.test
      - ./log/php:/var/log/php
    environment:
      TARGET: "${TARGET}"

  mariadb:
    image: mariadb
    container_name: wordpress_mariadb
    restart: always
    volumes:
      - ./conf/mariadb/initdb.d:/docker-entrypoint-initdb.d:ro
      - ./log/mariadb:/var/log/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: changeme
